### PR TITLE
STEPS interface Extension

### PR DESCRIPTION
**Pull request by fprados**
I have added more options to STEPS and I have created the seg_CalcNCC interface

### CODE REVIEW

**Comment by mmodat** [comment]
We will need to check and correct what these changes are breaking in NiftyPipe. The split of BinaryMaths into two interfaces (BinaryMaths and BinaryMathsInteger) is likely to affect a few scripts, e.g. steps.

**Comment by mmodat** [comment]
Also, the seg_DetectLesions does not seem to be in the NiftySeg open source version. Should the interface be here? What is the plan with this executable?

**Comment by fprados** [comment]
Hi,

I did the split because if you did seg_maths mask.nii.gz -ero 3.000000000000 mask_eroded.nii.gz, it didn't do anything, and it was a big issue for perform_bias_correction and another pipelines

I will ask if I can make public available seg_DetectLesions.

**Comment by fprados** [comment]
The files affected are:
pipelines/perform_bias_field_correction.py
pipelines/perform_dti_processing_drc_protocol.py
pipelines/perform_noddi_processing.py
interfaces/niftk/functional.py
interfaces/niftk/gif.py
interfaces/niftk/diffusion.py

I have corrected them in my fork branch.

**Comment by fprados** [comment]
I have included the changes suggested by Nico, now I'm accomplishing the code style

My master branch in cmiclab has all the corrections

**Pull request merged**
